IMAGE: python:3.5

SCRIPT:
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip install coverage flake8
  - cp settings.ini.example settings.ini
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test
  - coverage report
  - flake8
